
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: "daily"
